#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0

# Configure addresses obtained from debconf
db_get bootmail/recipients || true
if [ -n "$RET" ]; then
	echo "$RET" > /etc/bootmail/recipients
fi

# Configure public keys obtained from debconf
db_get bootmail/gpgkeys || true
if [ -n "$RET" ]; then
	echo "$RET" > /etc/bootmail/gpgkeys
fi

# Flag to keep bootmail from running at installation time
touch /var/run/.bootmail-just-installed

#DEBHELPER#

# vi: syntax=sh ts=4 noexpandtab
