#!/bin/sh -e

. /usr/share/debconf/confmodule
db_version 2.0

# Configure addresses obtained from debconf
db_get bootmail/recipients || true
if [ -n "$RET" ]; then
	echo "$RET" > /etc/bootmail/recipients
else
	rm -f /etc/bootmail/recipients
fi

# Create gpg keys for mail signing, if not already setup
if [ ! -e /var/lib/bootmail/key.pub ] || [ ! -e /var/lib/bootmail/key.sec ]; then
	# Setup the directory
	mkdir -p -m 700 /var/lib/bootmail
	chown root:root /var/lib/bootmail
	chmod 700 /var/lib/bootmail
	# Generate a passphrase
	if [ ! -e /var/lib/bootmail/key.passphrase ]; then
		head -c 128 /dev/urandom | sha512sum | sed "s/ .*//" > /var/lib/bootmail/key.passphrase
        fi
	# Generate the keys from configuration; note that this will block until there's enough entropy!
	gpg --batch --passphrase-file /var/lib/bootmail/key.passphrase --gen-key /var/lib/bootmail/key.config
fi

#DEBHELPER#

# vi: syntax=sh ts=4 noexpandtab
