#!/bin/sh -e
#
#    bootmail - email some people when this system (re)boots
#
#    Copyright (C) 2011 Dustin Kirkland <kirkland@ubuntu.com>
#
#    Authors:
#        Dustin Kirkland <kirkland@ubuntu.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

print_mail_text() {
	# Print the header
	echo "$subject"
	echo
	# Update the motd now, so that it's ready when we append it
	[ -d /etc/update-motd.d ] && run-parts --lsbsysinit /etc/update-motd.d > /etc/motd
	# Concatenate all specified boot logs
	if [ -f "/etc/bootmail/logs" ]; then
		for i in $(cat /etc/bootmail/logs); do
			echo
			echo "=================="
			echo "[$i]:"
			echo "=================="
			cat "$i"
			echo "=================="
			echo
		done
	fi
}


# This should be comma-separated, and can be configured via debconf:
#  sudo dpkg-reconfigure bootmail
recipients=
[ -f /etc/bootmail/recipients ] && recipients="$(cat /etc/bootmail/recipients)"
if [ -z "$recipients" ]; then
	echo "No recipients defined in [/etc/bootmail/recipients]" 1>&2
	exit 0
fi
hostname=$(hostname -f)
date=$(date)
subject="bootmail: [$hostname] booted on [$date]"
# Must use the sed to ensure the mail renders properly in most readers
print_mail_text | sed -e "s/[^[:print:]]//g" | rootsign | mail -s "$subject" "$recipients" -- -F "Bootmail" -f "noreply@$hostname"
